// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPZzmGwGaBuMJgkzyeL7U5vMVQAoftadA',
    appId: '1:843180879103:web:41073080400be3460b70ca',
    messagingSenderId: '843180879103',
    projectId: 'social-app-47f28',
    authDomain: 'social-app-47f28.firebaseapp.com',
    storageBucket: 'social-app-47f28.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdF_mn8mYJq06hEsMrBuNUaJXPYI3iWso',
    appId: '1:843180879103:android:1338a316ffb22fc10b70ca',
    messagingSenderId: '843180879103',
    projectId: 'social-app-47f28',
    storageBucket: 'social-app-47f28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOP5tMiuyHqQ5avw2rv7-_Q0nOhldkpn8',
    appId: '1:843180879103:ios:508d5b10afc0b4460b70ca',
    messagingSenderId: '843180879103',
    projectId: 'social-app-47f28',
    storageBucket: 'social-app-47f28.appspot.com',
    androidClientId: '843180879103-ap173gtvp7dj7obgih1bmkdbu92gnld9.apps.googleusercontent.com',
    iosClientId: '843180879103-oc9jdmfr235eo2nkba1n2lmt08mufr4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOP5tMiuyHqQ5avw2rv7-_Q0nOhldkpn8',
    appId: '1:843180879103:ios:b545a9b45ae0b6ea0b70ca',
    messagingSenderId: '843180879103',
    projectId: 'social-app-47f28',
    storageBucket: 'social-app-47f28.appspot.com',
    androidClientId: '843180879103-ap173gtvp7dj7obgih1bmkdbu92gnld9.apps.googleusercontent.com',
    iosClientId: '843180879103-lahproq3ufsaul513trfhfdnqkp7deat.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
